/*
 * GlowneOkno.java
 *
 * Created on 29 kwiecień 2008, 04:05
 */

package wypozyczalniaForma;

import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;

/**
 *
 * @author  Luke
 */
public class GlowneOkno extends javax.swing.JFrame {
    
    /** Creates new form GlowneOkno */
    public GlowneOkno() {
        initComponents();
    }

    public GlowneOkno(WypozyczalniaForma aThis) {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZarzadzanieWypozyczeniami = new javax.swing.JFrame();
        calendarComboBox_od = new com.imagine.component.calendar.CalendarComboBox();
        calendarComboBox_do = new com.imagine.component.calendar.CalendarComboBox();
        jLabel_od = new javax.swing.JLabel();
        jLabel_do = new javax.swing.JLabel();
        jLabel_info = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_error = new javax.swing.JLabel();
        jRadioButton_przyjete = new javax.swing.JRadioButton();
        jRadioButton_zrealizowane = new javax.swing.JRadioButton();
        jRadioButton_doOdbioru = new javax.swing.JRadioButton();
        jRadioButton_pozyczone = new javax.swing.JRadioButton();
        jRadioButton_wszystkie = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        ZarzadzanieWypozyczeniami.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ZarzadzanieWypozyczeniami.setName("ZarzadzanieWypozyczeniami"); // NOI18N

        calendarComboBox_od.setName("calendarComboBox_od"); // NOI18N

        calendarComboBox_do.setName("calendarComboBox_do"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wypozyczalniaForma.WypozyczalniaForma.class).getContext().getResourceMap(GlowneOkno.class);
        jLabel_od.setText(resourceMap.getString("jLabel_od.text")); // NOI18N
        jLabel_od.setName("jLabel_od"); // NOI18N

        jLabel_do.setText(resourceMap.getString("jLabel_do.text")); // NOI18N
        jLabel_do.setName("jLabel_do"); // NOI18N

        jLabel_info.setText(resourceMap.getString("jLabel_info.text")); // NOI18N
        jLabel_info.setName("jLabel_info"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Imię", "Nazwisko", "PESEL", "Data zamówienia", "Stan zamówienia", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jLabel_error.setName("jLabel_error"); // NOI18N

        jRadioButton_przyjete.setText(resourceMap.getString("jRadioButton_przyjete.text")); // NOI18N
        jRadioButton_przyjete.setName("jRadioButton_przyjete"); // NOI18N

        jRadioButton_zrealizowane.setText(resourceMap.getString("jRadioButton_zrealizowane.text")); // NOI18N
        jRadioButton_zrealizowane.setName("jRadioButton_zrealizowane"); // NOI18N

        jRadioButton_doOdbioru.setText(resourceMap.getString("jRadioButton_doOdbioru.text")); // NOI18N
        jRadioButton_doOdbioru.setName("jRadioButton_doOdbioru"); // NOI18N

        jRadioButton_pozyczone.setText(resourceMap.getString("jRadioButton_pozyczone.text")); // NOI18N
        jRadioButton_pozyczone.setName("jRadioButton_pozyczone"); // NOI18N

        jRadioButton_wszystkie.setSelected(true);
        jRadioButton_wszystkie.setText(resourceMap.getString("jRadioButton_wszystkie.text")); // NOI18N
        jRadioButton_wszystkie.setName("jRadioButton_wszystkie"); // NOI18N

        javax.swing.GroupLayout ZarzadzanieWypozyczeniamiLayout = new javax.swing.GroupLayout(ZarzadzanieWypozyczeniami.getContentPane());
        ZarzadzanieWypozyczeniami.getContentPane().setLayout(ZarzadzanieWypozyczeniamiLayout);
        ZarzadzanieWypozyczeniamiLayout.setHorizontalGroup(
            ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_error, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                            .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                                .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_przyjete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton_zrealizowane)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton_doOdbioru))
                                    .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_do)
                                        .addComponent(calendarComboBox_do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_pozyczone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_wszystkie))))
                    .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_od)
                            .addComponent(calendarComboBox_od, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_info))))
                .addContainerGap())
        );
        ZarzadzanieWypozyczeniamiLayout.setVerticalGroup(
            ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZarzadzanieWypozyczeniamiLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_od)
                    .addComponent(jLabel_do))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarComboBox_od, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendarComboBox_do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(ZarzadzanieWypozyczeniamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_przyjete)
                    .addComponent(jRadioButton_zrealizowane)
                    .addComponent(jRadioButton_doOdbioru)
                    .addComponent(jRadioButton_pozyczone)
                    .addComponent(jRadioButton_wszystkie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(wypozyczalniaForma.WypozyczalniaForma.class).getContext().getActionMap(GlowneOkno.class, this);
        jMenuItem1.setAction(actionMap.get("createAccount")); // NOI18N
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuItem1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuItem1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuItem1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1AncestorAdded

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        WypozyczalniaForma kreator = new WypozyczalniaForma();
        kreator.show(new UtworzKonto());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        WypozyczalniaForma blok = new WypozyczalniaForma();
        blok.show(new ZablokujKonto()) ;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        WypozyczalniaForma zarzadzanie = new WypozyczalniaForma();
        zarzadzanie.show( new ZarzadzajWypozyczeniami()); 
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        WypozyczalniaForma zarzadzanie = new WypozyczalniaForma();
        zarzadzanie.show( new ZarzadzajWypozyczeniami()); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlowneOkno().setVisible(true);
            }
        });
    }

    @Action
    public void createAccount() {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ZarzadzanieWypozyczeniami;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBox_do;
    private com.imagine.component.calendar.CalendarComboBox calendarComboBox_od;
    private javax.swing.JLabel jLabel_do;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JLabel jLabel_od;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton_doOdbioru;
    private javax.swing.JRadioButton jRadioButton_pozyczone;
    private javax.swing.JRadioButton jRadioButton_przyjete;
    private javax.swing.JRadioButton jRadioButton_wszystkie;
    private javax.swing.JRadioButton jRadioButton_zrealizowane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
