/*
 * ZablokujKonto.java
 *
 * Created on 29 kwiecień 2008, 04:02
 */

package wypozyczalniaForma;

import java.util.ArrayList;
import javax.swing.JFrame;
import wypozyczalnia.dao.StanKonta;
import wypozyczalnia.to.KontoTO;
import wypozyczalnia.to.KlientTO;

/**
 *
 * @author  Luke
 */
public class ZablokujKonto extends javax.swing.JFrame {


private ArrayList<KontoTO> bazaKonta;
private ArrayList<KlientTO> bazaKlienci;

private void fill(String theImie, String theNazwisko, String theAdresMailowy, String theNrPeselKlienta){
    KlientTO nowy = new KlientTO();
    nowy.setAdresMailowy(theAdresMailowy);
    nowy.setImie(theImie);
    nowy.setNazwisko(theNazwisko);
    nowy.setNrPeselKlienta(theNrPeselKlienta);
    bazaKlienci.add(nowy);
    KontoTO nowe = new KontoTO();
    nowe.setNrKonta(12);
    nowe.setNrPeselKlienta(theNrPeselKlienta);
    nowe.setStanKonta(StanKonta.AKTYWNE);
    bazaKonta.add(nowe);
}
private KontoTO findKonto(String pesel){
    KontoTO znalezione = new KontoTO();
    for(KontoTO konto : bazaKonta){
        if(konto.getNrPeselKlienta().compareTo(pesel)==0)
            return konto;
    }
    return null;
}

private KlientTO findKlient(String pesel){
    KlientTO znalezione = new KlientTO();
    for(KlientTO klient : bazaKlienci){
        if(klient.getNrPeselKlienta().equals(pesel))
            return klient;
    }
    return null;
}
    /** Creates new form ZablokujKonto */
    public ZablokujKonto() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        bazaKlienci = new ArrayList<KlientTO>();
        bazaKonta = new ArrayList<KontoTO>();
        fill("Łukasz", "Prasoł", "lprasol@gmail.com", "85102001252");
        fill("Tomasz", "Stadnicki", "sirtopp@gmail.com", "85122109051");
        fill("Nemo", "Czyli nikt", "nobody@gmail.com", "12345678901");

    }

    ZablokujKonto(JFrame a) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        fill("Łukasz", "Prasoł", "lprasol@gmail.com", "85102001252");
        fill("Tomasz", "Stadnicki", "sirtopp@gmail.com", "85121212121");
                        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZablokujKonto().setVisible(true);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nrPesel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imieField = new javax.swing.JTextField();
        imieLabel = new javax.swing.JLabel();
        nazwiskoLabel = new javax.swing.JLabel();
        nazwiskoField = new javax.swing.JTextField();
        dataField = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wypozyczalniaForma.WypozyczalniaForma.class).getContext().getResourceMap(ZablokujKonto.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setName("jButton1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        nrPesel.setText(resourceMap.getString("nrPesel.text")); // NOI18N
        nrPesel.setName("nrPesel"); // NOI18N
        nrPesel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nrPeselKeyReleased(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        imieField.setEditable(false);
        imieField.setText(resourceMap.getString("imieField.text")); // NOI18N
        imieField.setEnabled(false);
        imieField.setName("imieField"); // NOI18N

        imieLabel.setText(resourceMap.getString("imieLabel.text")); // NOI18N
        imieLabel.setName("imieLabel"); // NOI18N

        nazwiskoLabel.setText(resourceMap.getString("nazwiskoLabel.text")); // NOI18N
        nazwiskoLabel.setName("nazwiskoLabel"); // NOI18N

        nazwiskoField.setEditable(false);
        nazwiskoField.setText(resourceMap.getString("nazwiskoField.text")); // NOI18N
        nazwiskoField.setEnabled(false);
        nazwiskoField.setName("nazwiskoField"); // NOI18N

        dataField.setEditable(false);
        dataField.setText(resourceMap.getString("dataField.text")); // NOI18N
        dataField.setName("dataField"); // NOI18N

        dataLabel.setText(resourceMap.getString("dataLabel.text")); // NOI18N
        dataLabel.setName("dataLabel"); // NOI18N

        mailField.setEditable(false);
        mailField.setText(resourceMap.getString("mailField.text")); // NOI18N
        mailField.setEnabled(false);
        mailField.setName("mailField"); // NOI18N

        mailLabel.setText(resourceMap.getString("mailLabel.text")); // NOI18N
        mailLabel.setName("mailLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nrPesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imieLabel)
                            .addComponent(dataLabel)
                            .addComponent(mailLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazwiskoField)
                            .addComponent(imieField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(dataField)
                            .addComponent(mailField))))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nazwiskoLabel)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imieLabel)
                    .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwiskoLabel)
                    .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailLabel))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        imieLabel.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel3.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nrPeselKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrPeselKeyReleased
        String pesel = nrPesel.getText();
        
        if ( pesel.length() == 11){ 
            KontoTO konto;
            KlientTO klient;
            konto = findKonto(nrPesel.getText());
            klient = findKlient(nrPesel.getText());
            if(konto!=null && klient!= null){
                imieField.setEnabled(true);
                nazwiskoField.setEnabled(true);
                mailField.setEnabled(true);
                imieField.setText(klient.getImie());
                nazwiskoField.setText(klient.getNazwisko());
                mailField.setText(klient.getAdresMailowy());
                jButton1.setEnabled(true);
            }
        }
            else{
                imieField.setText("");
                nazwiskoField.setText("");
                mailField.setText("");
                jButton1.setEnabled(false);
            }
        
}//GEN-LAST:event_nrPeselKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZablokujKonto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataField;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField imieField;
    private javax.swing.JLabel imieLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField nazwiskoField;
    private javax.swing.JLabel nazwiskoLabel;
    private javax.swing.JTextField nrPesel;
    // End of variables declaration//GEN-END:variables
    
}
