
package wypozyczalnia.gui;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.SingleFrameApplication;
import wypozyczalnia.dao.StanKonta;
import wypozyczalnia.logika.zarzadzanieKontami.ZarzadzanieKontamiDelegacja;
import wypozyczalnia.logika.zarzadzanieKontami.ZarzadzanieKontamiWyjatek;
import wypozyczalnia.logika.zarzadzanieKontami.walidacja.WalidatorDanychKontaWyjatek;
import wypozyczalnia.to.zarzadzaniekontami.KontoTO;
import wypozyczalnia.to.zarzadzaniekontami.KlientTO;

/**
 *
 * @author  Luke
 */
public class ZablokujKonto extends javax.swing.JFrame {

private ZarzadzanieKontamiDelegacja zarzadzanieKontami = ZarzadzanieKontamiDelegacja.getInstance();

    /** Creates new form ZablokujKonto */
    public ZablokujKonto() {
        initComponents();

    }

    ZablokujKonto(SingleFrameApplication a) {
        initComponents();
                        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZablokujKonto().setVisible(true);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nrPesel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imieField = new javax.swing.JTextField();
        imieLabel = new javax.swing.JLabel();
        nazwiskoLabel = new javax.swing.JLabel();
        nazwiskoField = new javax.swing.JTextField();
        dataField = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        mailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wypozyczalnia.gui.WypozyczalniaForma.class).getContext().getResourceMap(ZablokujKonto.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setEnabled(false);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        nrPesel.setText(resourceMap.getString("nrPesel.text")); // NOI18N
        nrPesel.setName("nrPesel"); // NOI18N
        nrPesel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nrPeselKeyReleased(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        imieField.setEditable(false);
        imieField.setText(resourceMap.getString("imieField.text")); // NOI18N
        imieField.setEnabled(false);
        imieField.setName("imieField"); // NOI18N

        imieLabel.setText(resourceMap.getString("imieLabel.text")); // NOI18N
        imieLabel.setName("imieLabel"); // NOI18N

        nazwiskoLabel.setText(resourceMap.getString("nazwiskoLabel.text")); // NOI18N
        nazwiskoLabel.setName("nazwiskoLabel"); // NOI18N

        nazwiskoField.setEditable(false);
        nazwiskoField.setText(resourceMap.getString("nazwiskoField.text")); // NOI18N
        nazwiskoField.setEnabled(false);
        nazwiskoField.setName("nazwiskoField"); // NOI18N

        dataField.setEditable(false);
        dataField.setText(resourceMap.getString("dataField.text")); // NOI18N
        dataField.setName("dataField"); // NOI18N

        dataLabel.setText(resourceMap.getString("dataLabel.text")); // NOI18N
        dataLabel.setName("dataLabel"); // NOI18N

        mailField.setEditable(false);
        mailField.setText(resourceMap.getString("mailField.text")); // NOI18N
        mailField.setEnabled(false);
        mailField.setName("mailField"); // NOI18N

        mailLabel.setText(resourceMap.getString("mailLabel.text")); // NOI18N
        mailLabel.setName("mailLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nrPesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imieLabel)
                            .addComponent(dataLabel)
                            .addComponent(mailLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazwiskoField)
                            .addComponent(imieField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(dataField)
                            .addComponent(mailField))))
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nazwiskoLabel)
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imieLabel)
                    .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwiskoLabel)
                    .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailLabel))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        imieLabel.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel3.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nrPeselKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrPeselKeyReleased
        String pesel = nrPesel.getText();
        
        if ( pesel.length() == 11){ 
            try {
                KontoTO konto;
                KlientTO klient;
                boolean ret = zarzadzanieKontami.czyUzytkownikZarejestrowany(pesel);
                if (ret) {
                    konto = zarzadzanieKontami.zwrocDaneKonta(pesel);
                    klient = zarzadzanieKontami.zwrocDaneKlienta(pesel);
                    imieField.setEnabled(true);
                    nazwiskoField.setEnabled(true);
                    mailField.setEnabled(true);
                    imieField.setText(klient.getImie());
                    nazwiskoField.setText(klient.getNazwisko());
                    mailField.setText(klient.getAdresMailowy());
                    jButton1.setEnabled(true);
                }
            } catch (WalidatorDanychKontaWyjatek ex) {
                Logger.getLogger(ZablokujKonto.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ZarzadzanieKontamiWyjatek ex) {
                Logger.getLogger(ZablokujKonto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            else{
                imieField.setText("");
                nazwiskoField.setText("");
                mailField.setText("");
                jButton1.setEnabled(false);
            }
        
}//GEN-LAST:event_nrPeselKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZablokujKonto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataField;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField imieField;
    private javax.swing.JLabel imieLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField nazwiskoField;
    private javax.swing.JLabel nazwiskoLabel;
    private javax.swing.JTextField nrPesel;
    // End of variables declaration//GEN-END:variables
    
}
